### ISSUE TITLE
ocne cluster start hangs waiting for the Oracle Catalog to start

### ISSUE THREAD

**Issue by mgianatagh** [oracle-cne/ocne#147]
**Problem**:

An `ocne cluster start` hangs with the message below:

```
INFO[2024-11-03T13:26:29Z] Waiting for Oracle Catalog to start: waiting 
```

**Steps to Reproduce**

Create a global defaults file:
```
cat > ~/.ocne/test-global-defaults.yaml - <<EOF
autoStartUI: false
EOF
```

Create a cluster config file:
```
cat > ~/.ocne/test-cluster-config.yaml - <<EOF
name: mickey
kubernetesVersion: 1.29
headless: true
password: "$6$ocne$6ReF22fGSN6cyepwGW.7hwBdQw7/Ho/PYXSeT3zPc0bPycWXY4wl1uWFG47FESG8kdA3vk6PG9mAElcI2stVT1"
communityCatalog: true
catalogs:
  - name: "WebLogic Operator"
    namespace: ocne-system
    uri: https://oracle.github.io/weblogic-kubernetes-operator 
    protocol: helm
applications:
  - name: weblogic-operator
    release: weblogic-operator
    catalog: "WebLogic Operator"
    namespace: weblogic-operator
EOF
```

Start the cluster:
```
OCNE_DEFAULTS=~/.ocne/test-global-defaults.yaml ocne cluster start --config ~/.ocne/test-cluster-config.yaml
```

**Analysis**

The `WaitForInternalCatalogInstall` function is waiting for a deployment with the incorrect name.
