### ISSUE TITLE
Instance Shape Customizations Not Being Applied In Cluster Template Command

### ISSUE THREAD

**Issue by George-Aeillo** [oracle-cne/ocne#245]
When the `cluster template` command is used with the oci provider, the user has the ability to customize their shape for their control plane and worker instances, as seen in the snippet below. However when these options are applied with the `cluster template -c custom.yaml`command, the resulting template does not have these custom image shapes. 

Example of custom.yaml file
```
providerConfig:
  oci:
    controlPlaneShape:
      shape: VM.Standard.A1.Flex
      ocpus: 2
    workerShape:
      shape: VM.Standard.A1.Flex
```

Resources in resulting template:
```
...
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: OCIMachineTemplate
metadata:
  name: "test"
  namespace: "ocne"
spec:
  template:
    spec:
      imageId: ""
      compartmentId: ""
      shape: "VM.Standard.E4.Flex"
      shapeConfig:
        ocpus: "4"
      metadata:
...
```
