### ISSUE TITLE
OCI provider should only configure each unique subnet only once in the oci-ccm configuration file

### ISSUE THREAD

**Issue by dkrasins** [oracle-cne/ocne#406]
The OCI-CCM configuration looks like this:
```
auth:
    fingerprint: ...
    key: |
        -----BEGIN PRIVATE KEY-----
        ...
        -----END PRIVATE KEY-----
    passphrase: ...
    region: us-ashburn-1
    tenancy: ocid1.tenancy.oc1..aaaaaaaaqe...
    useInstancePrincipals: false
    user: ocid1.user.oc1..aaaaaaaaeg...
compartment: ocid1.compartment.oc1..aaaaaaaalo...
loadBalancer:
    securityListManagementMode: None
    subnet1: ocid1.subnet.oc1.iad.aaaaaaaa...
vcn: ocid1.vcn.oc1.iad.amaaaaaa6....
```
It is possible to have two subnets under the `loadBalancer` section.  Until recently, using the same subnet OCID twice worked just fine.  Recently, that stopped working.  Now, the oci-cloud-controller pod reports an error when trying to create the LB.  To remedy this, each unique subnet should be listed only once under the `loadBalancer` section.
