### ISSUE TITLE
OCI provider should validate more provider configuration options before trying to create a cluster

### ISSUE THREAD

**Issue by dkrasins** [oracle-cne/ocne#59]
Clusters deployed using the oci provider require that OCI-CCM be deployed and correctly configured in the workload cluster.  If it is not, `ocne cluster start` will time out due to the nodes never fully initializing.  The reason for this is that Cluster API applies taints to nodes that the node controller for OCI-CCM clears.  Until those taints are removed, pods will fail to schedule.

The specific fields causing this issue are:
```
providers:
  oci:
    compartment: <your compartment>
    vcn: <your vcn>
    loadBalancer:
      subnet1: <your subnet>
      subnet2: <your other subnet>
```

The oci cluster driver should ensure that these fields are set before attempting to start the cluster.  They are required, and it is hard to figure out what is wrong if they are not provided.
